name: Unit tests

runs:
  using: "composite"
  steps:
  - name: Install Go
    uses: actions/setup-go@v5
    with:
      go-version: ${{ env.GO_VERSION }}

  - name: Check out code into the Go module directory
    uses: actions/checkout@v4

  - name: Run tests
    shell: bash
    run: make unit-test