apiVersion: osrm.itayankri/v1alpha1
kind: OSRMCluster
metadata:
  name: multi-profile-example
spec:
  pbfUrl: https://download.geofabrik.de/australia-oceania/marshall-islands-latest.osm.pbf
  profiles:
  - name: car
    endpointName: driving
    minReplicas: 1
    maxReplicas: 10
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 500Mi
  - name: bicycle
    endpointName: cycling
    minReplicas: 1
    maxReplicas: 4
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  - name: foot
    endpointName: foot
    minReplicas: 1
    maxReplicas: 2
    resources:
      limits:
        cpu: 600m
        memory: 600Mi
  service:
    type: LoadBalancer
    annotations:
      example-annotation: "example-annotation"
    exposingServices: ["route", "table", "match"]
  persistence:
    storage: 100Mi
    storageClassName: standard