apiVersion: osrm.itayankri/v1alpha1
kind: OSRMCluster
metadata:
  name: single-profile-example
spec:
  mapBuilder:
    image: itayankri/osrm-builder:osrm-v5.27.1
    extractOptions: "--parse-conditional-restrictions"
    customizeOptions: "--parse-conditionals-from-now 1727194872"
  # pbfUrl: https://download.geofabrik.de/australia-oceania/marshall-islands-latest.osm.pbf
  pbfUrl: https://download.geofabrik.de/australia-oceania/marshall-islands-250713.osm.pbf
  profiles:
  - name: foot
    endpointName: foot
    minReplicas: 1
    maxReplicas: 4
  service:
    exposingServices: ["route", "table", "match"]
  persistence:
    storage: "1000Mi"
    storageClassName: standard
    accessMode: ReadWriteOnce