apiVersion: osrm.itayankri/v1alpha1
kind: OSRMCluster
metadata:
  name: single-profile-example
spec:
  mapBuilder:
    image: itayankri/osrm-builder:osrm-v5.27.1
    extractOptions: "--parse-conditional-restrictions"
  pbfUrl: https://download.geofabrik.de/australia-oceania/marshall-islands-latest.osm.pbf
  profiles:
  - name: foot
    endpointName: foot
    minReplicas: 2
    maxReplicas: 4
  service:
    exposingServices: ["route", "table", "match"]
  persistence:
    storage: "1000Mi"
    storageClassName: standard
    accessMode: ReadWriteOnce
    