apiVersion: osrm.itayankri/v1alpha1
kind: OSRMCluster
metadata:
  name: single-profile-example
spec:
  mapBuilder:
    image: itayankri/osrm-builder:osrm-v5.27.1
    env:
    - name: EXAMPLE
      value: "--max-matching-size=1000"
  pbfUrl: https://download.geofabrik.de/australia-oceania/marshall-islands-210101.osm.pbf
  profiles:
  - name: foot
    endpointName: foot
    minReplicas: 1
    maxReplicas: 4
  service:
    exposingServices: ["route", "table", "match"]
  persistence:
    storage: "1000Mi"
    storageClassName: standard
    accessMode: ReadWriteOnce
    