name: PR

on:
  pull_request:
    branches: [ master ]

env:
  GO_VERSION: 1.24.13
  K8S_VERSION: v1.33.0
  ENV: test

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run test
      uses: ./.github/actions/unit-test

  integration-tests:
    name: Integration + E2E tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      uses: ./.github/actions/integration-test
